// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5xrXBFRoKx9ZwgF07xEaRWjOkQcqd0r4 ',
    appId: '1:701213094891:android:e2f9123c3e7cb496029fae',
    messagingSenderId: '701213094891',
    projectId: 'calendar-e2d4d',
    storageBucket: 'calendar.appspot.com',
  );
}
